import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" data-theme="dracula">
      <body
        className={`${inter}`}
      >
        <Toaster />
        <div className="flex justify-center items-center min-h-screen my-5">
          {children}
        </div>
      </body>
    </html>
  );
}
